web:
  upload-path: D:/file/

server:
  port: 8011
  servlet:
    session:
      timeout: 10m

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sshy_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: file:${web.upload-path}

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.sshy.api.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  path: D:/sshylog/logs

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  page-size-zero: true



